In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 30, 3)

In [5]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
arr[3]

9

pegando o eleentos atrvesz do indice dele

In [10]:
arr[2:5]

array([ 6,  9, 12])

pegando elementos com inicio do indice 2 ate o 5

In [13]:
arr[:5]

array([ 0,  3,  6,  9, 12])

In [15]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [17]:
arr[2:] = 100

Todos os elementos a partir do indice 2 terao valor 100

In [20]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

Vale de mesma forma para arrays bidimencionais

In [23]:
arr = np.arange(50).reshape(5, 10)

In [27]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [29]:
arr.shape

(5, 10)

In [31]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

[mostrara todos os elemnetos ate a 3 LINHA][mostrara todos os elementos de todas as COLUNAS]

In [34]:
arr[:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [50]:
arr2 = arr[:3].copy()

In [52]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [54]:
arr2[:] = 100

In [56]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [62]:
arr[:3]

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [64]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [68]:
arr[1:4,5:]

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 35,  36,  37,  38,  39]])

Tambem pode fazer os fatiamentos de linha e coluna saparando por virgula
teste[LINHA,COLUNA]

In [73]:
arr

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [75]:
arr > 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

utilizando operacoes logicas

In [80]:
bol = arr > 50

In [82]:
arr[bol]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

O bol tem que tem que encaixar no arr

ARR[BOL] resultara nos elementos dados como TRUE

In [86]:
array = np.linspace(0, 100, 30)

In [88]:
array

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [90]:
array.shape

(30,)

In [92]:
array = array.reshape(3, 10)

In [94]:
array

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [96]:
array.shape

(3, 10)

In [98]:
array[0:2, 2]

array([ 6.89655172, 41.37931034])