In [4]:
import numpy as np

importa a biblioteca numpy e atrui o nom np

In [7]:
minha_lista = [1, 2, 3]

In [11]:
minha_lista

[1, 2, 3]

In [13]:
np.array(minha_lista)

array([1, 2, 3])

Converte uma lista em um array

In [20]:
minha_matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Para criar uma sequencia de numeros

SHIFT + TAB para documentacao

In [28]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [32]:
np.zeros(3)

array([0., 0., 0.])

Para criar uma matriz so de zeros

In [35]:
arr = np.zeros(3)

In [37]:
arr

array([0., 0., 0.])

In [39]:
arr = np.zeros((5, 5))

In [41]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Passa uma tupla para criar uma matriz de zeros

In [44]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Para criar matriz de 1

In [47]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Criarcao de matriz identidade 

In [50]:
np.linspace(0, 10, 2)

array([ 0., 10.])

np.linspace(0, 10, 3)

Retorna números uniformemente espaçados em um intervalo especificado

In [61]:
np.random.rand(5)

array([0.91986653, 0.76636023, 0.31717343, 0.5300355 , 0.64596601])

Cria numeros aleotorios de 0 a 1 seguindo uma distribuicao uniforme

In [64]:
np.random.rand(5) * 100

array([81.26022066, 98.57958919, 95.24658573, 71.6650968 , 51.00002403])

In [66]:
np.random.rand(5, 4)

array([[0.12500296, 0.45091673, 0.51521311, 0.60658357],
       [0.50612143, 0.23730964, 0.87178902, 0.64273321],
       [0.33810559, 0.85212143, 0.27752857, 0.32523384],
       [0.19046888, 0.25139419, 0.8252416 , 0.28102323],
       [0.8055755 , 0.97375756, 0.59455457, 0.31913911]])

np.random.randn(4)

numeros aleotorios sem distribuicao uniforme

In [75]:
np.random.randint(0, 100, 10)

array([ 4, 64, 62, 95, 26, 87, 18, 64, 52, 97])

numeros inteiros tirados de uma distribuicao aleatoria

In [78]:
np.random.rand(5) * 100

array([37.10342055, 86.35156341, 21.22872587, 99.42863367, 56.80421107])

In [82]:
np.round(np.random.rand(5),0)

array([0., 1., 0., 0., 1.])

In [84]:
np.round(np.random.rand(5)*100,0)

array([ 4., 79., 44., 32., 79.])

Atributos

In [89]:
arr = np.random.rand(25)

In [91]:
arr

array([0.20592129, 0.14613628, 0.4634337 , 0.74043241, 0.14779949,
       0.16259952, 0.70837316, 0.6667932 , 0.97047062, 0.53354494,
       0.39164909, 0.5079926 , 0.76811879, 0.46982089, 0.46857416,
       0.84137417, 0.8389281 , 0.99293542, 0.38372941, 0.16110322,
       0.76690232, 0.67388444, 0.2096017 , 0.89693466, 0.11617954])

Dá uma nova forma a uma matriz sem alterar seus dados

In [113]:
arr = arr.reshape((5,5))

In [115]:
arr

array([[0.20592129, 0.14613628, 0.4634337 , 0.74043241, 0.14779949],
       [0.16259952, 0.70837316, 0.6667932 , 0.97047062, 0.53354494],
       [0.39164909, 0.5079926 , 0.76811879, 0.46982089, 0.46857416],
       [0.84137417, 0.8389281 , 0.99293542, 0.38372941, 0.16110322],
       [0.76690232, 0.67388444, 0.2096017 , 0.89693466, 0.11617954]])

In [117]:
arr.shape

(5, 5)

O formato de uma matriz é o número de elementos em cada dimensão

In [120]:
arr.max()

0.9929354181453531

encontra o maior valor

In [127]:
arr.min()

0.11617953920499646

encontra o menor valor

In [132]:
arr.argmax()

17

Retorna os índices dos valores máximos

In [137]:
arr.argmin()


24

Retorna o índice do menor valor